package com.example.evan.androidviewertemplates.firebase_classes;

import java.util.ArrayList;
import java.util.Map;

/**
 * Created by Katherine on 1/12/2018.
 */

public class CalculatedTeamData extends Object {

    public Boolean canScoreBothSwitchSidesAuto;
    public Float RScoreAgility;
    public Float RScoreDefense;
    public Float RScoreDrivingAbility;
    public Float RScoreSpeed;
    public Float actualNumRPs;
    public Float allianceSwitchFailPercentageAuto;
    public Float allianceSwitchFailPercentageTele;
    public Float allianceSwitchSuccessPercentageAuto;
    public Float allianceSwitchSuccessPercentageTele;
    public Float autoRunPercentage;
    public Float avgAgility;
    public Float avgAllianceSwitchCubesAuto;
    public Float avgAllianceSwitchCubesTele;
    public Float avgAllianceSwitchTimeAuto;
    public Float avgAllianceSwitchTimeTele;
    public Float avgAllianceTimeAuto;
    public Float avgAllianceTimeTele;
    public Float avgClimbTime;
    public Float avgCubesPlacedInScaleAuto;
    public Float avgCubesPlacedInScaleTele;
    public Float avgCubesSpilledAuto;
    public Float avgCubesSpilledTele;
    public Float avgDefense;
    public Float avgDrivingAbility;
    public Float avgNumAlliancePlatformIntakeAuto;
    public Float avgNumAlliancePlatformIntakeTele;
    public Float avgNumBadDecisions;
    public Float avgNumCubesFumbledAuto;
    public Float avgNumCubesFumbledTele;
    public Float avgNumElevatedPyramidIntakeAuto;
    public Float avgNumElevatedPyramidIntakeTele;
    public Float avgNumExchangeInputTele;
    public Float avgNumGoodDecisions;
    public Float avgNumGroundIntakeTele;
    public Float avgNumGroundPortalIntakeTele;
    public Float avgNumGroundPyramidIntakeAuto;
    public Float avgNumGroundPyramidIntakeTele;
    public Float avgNumHumanPortalIntakeTele;
    public Float avgNumOpponentPlatformIntakeAuto;
    public Float avgNumOpponentPlatformIntakeTele;
    public Float avgNumRetrunIntakeTele;
    public Float avgNumReturnIntakeTele;
    public Float avgOpponentSwitchCubesAuto;
    public Float avgOpponentSwitchCubesTele;
    public Float avgOpponentSwitchTimeTele;
    public Float avgOpponentTimeAuto;
    public Float avgOpponentTimeTele;
    public Float avgScaleTimeAuto;
    public Float avgScaleTimeTele;
    public Float avgSpeed;
    public Float climbPercentage;
    public Float disabledPercentage;
    public Float dysfunctionalPercentage;
    public Float firstPickAbility;
    public Float firstPickAbiltiy;
    public Float incapacitatedPercentage;
    public Float lfmActualNumRPs;
    public Float lfmAvgAgility;
    public Float lfmAvgAllaicneSwitchCubesTele; //todo Delete later
    public Float lfmAvgAllianceSwitchCubesAuto;
    public Float lfmAvgAllianceSwitchCubesTele;
    public Float lfmAvgAllianceSwitchTimeAuto;
    public Float lfmAvgAllianceSwitchTimeTele;
    public Float lfmAvgCubesPlacedInScaleAuto;
    public Float lfmAvgCubesPlacedInScaleTele;
    public Float lfmAvgCubesSpilledAuto;
    public Float lfmAvgCubesSpilledTele;
    public Float lfmAvgDefense;
    public Float lfmAvgDrivingAbility;
    public Float lfmAvgGroundIntakeTele;
    public Float lfmAvgNumAlliancePlatformIntakeAuto;
    public Float lfmAvgNumAlliancePlatformIntakeTele;
    public Float lfmAvgNumBadDecisions;
    public Float lfmAvgNumBluePlatformintakeTele; //todo Delete later
    public Float lfmAvgNumBubesFumbledTele;
    public Float lfmAvgNumCubesFumbledAuto;
    public Float lfmAvgNumCubesFumbledTele;
    public Float lfmAvgNumElevatedPyramidIntakeAuto;
    public Float lfmAvgNumElevatedPyramidIntakeTele;
    public Float lfmAvgNumExchangeInputTele;
    public Float lfmAvgNumGoodDecicions;
    public Float lfmAvgNumGoodDecisions;
    public Float lfmAvgNumGroundIntakeTele;
    public Float lfmAvgNumGroundPortalIntakeTele;
    public Float lfmAvgNumGroundPyramidIntakeAuto;
    public Float lfmAvgNumGroundPyramidIntakeTele;
    public Float lfmAvgNumHumanPortalIntakeTele;
    public Float lfmAvgNumOpponentPlatformIntakeAuto;
    public Float lfmAvgNumOpponentPlatformIntakeTele;
    public Float lfmAvgNumPyramidIntakeAuto;
    public Float lfmAvgNumPyramidintakeTele;
    public Float lfmAvgNumReturnIntakeTele;
    public Float lfmAvgOpponentSwitchCubesAuto;
    public Float lfmAvgOpponentSwitchCubesTele;
    public Float lfmAvgOpponentSwitchTimeTele;
    public Float lfmAvgScaleTimeAuto;
    public Float lfmAvgScaleTimeTele;
    public Float lfmAvgSpeed;
    public Float numSuccessfulClimbs;
    public Float opponentSwitchFailPercentageTele;
    public Float opponentSwitchSuccessPercentageTele;
    public Float pitAvgDriveTime;
    public Float pitAvgRampTime;
    public Float predictedClimb;
    public Float predictedNumRPs;
    public Float predictedPark;
    public Float scaleFailPercentageAuto;
    public Float scaleFailPercentageTele;
    public Float scaleSuccessPercentageAuto;
    public Float scaleSuccessPercentageTele;
    public Float secondPickAbility;
    public Float totalNumRobotLiftAttempts;
    public Integer actualSeed;
    public Integer number;
    public Integer predictedNumAllianceSwitchCubesAuto;
    public Integer predictedNumScaleCubesAuto;
    public Integer predictedSeed;
    public Integer predictedTotalNumRPs;
    public Integer totalNumBadDecisions;
    public Integer totalNumGoodDecisions;
    public Integer totalNumParks;
    public Integer totalNumRobotGroundLiftAttempts;
    public Integer totalNumRobotsGroundLifted;
    public Integer totalNumRobotsLiftAttempts;
    public Integer totalNumRobotsLifted;

}